_target_: __main__.ECGtoLabelviaDistrbution
config: 
  classification: None 
  future_mean_model_pth: /storage/chandak/Silver/src/outputs/2024-03-03/13-27-17/checkpoints/epoch_018.ckpt
  future_std_model_pth: /storage/chandak/Silver/src/outputs/2024-03-03/13-26-34/checkpoints/epoch_004.ckpt
  label: '${dataset.config.label}'
objective: 
  _target_: None